#!/bin/bash

# For every ipynb file in the git index:
# - apply black and flake8
# - export the notebook to a Python script in folder 'python'
# - and add it to the git index

if git diff --cached --name-status | \
    awk '$1 != "D" { print $2 }' | \
    grep -E '.*\.(ipynb|py)$' \
      2>/dev/null ; then

  jupytext --from ipynb --pipe black --pre-commit
  jupytext --from ipynb --to jupytext//py --sync --pre-commit

  for nb in $(git diff --cached --name-status | \
                awk '$1 != "D" { print $2 }' | \
                grep '.*\.ipynb$'); do
    (
      nb_dir="$(dirname -- "$nb")"
      nb_file="$(basename -- "$nb")"
      nb_base="${nb_file%.*}"

      (>&2 echo -n '[NbConvertApp]' )
      (>&2 echo "Converting $nb to ${nb_dir}/${nb_base}.html ..." )

      cd "$nb_dir" || exit 1
      mkdir -p jupytext
      if ! grep '\*.html' jupytext/.gitignore; then
        echo '# ignore html files' >> jupytext/.gitignore
        echo  '*.html' >> jupytext/.gitignore
      fi

      jupyter-nbconvert --to html --output-dir jupytext "$nb_file"
    )
  done
fi

exit 0